# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 624)
        self.comboBox_year = QtWidgets.QComboBox(Form)
        self.comboBox_year.setGeometry(QtCore.QRect(230, 100, 90, 30))
        self.comboBox_year.setObjectName("comboBox_year")
        self.comboBox_month = QtWidgets.QComboBox(Form)
        self.comboBox_month.setGeometry(QtCore.QRect(370, 100, 90, 30))
        self.comboBox_month.setObjectName("comboBox_month")
        self.pushButton_last_month = QtWidgets.QPushButton(Form)
        self.pushButton_last_month.setGeometry(QtCore.QRect(80, 100, 30, 30))
        self.pushButton_last_month.setObjectName("pushButton_last_month")
        self.pushButton_next_month = QtWidgets.QPushButton(Form)
        self.pushButton_next_month.setGeometry(QtCore.QRect(590, 100, 30, 30))
        self.pushButton_next_month.setObjectName("pushButton_next_month")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(75, 131, 551, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "打卡日历"))
        self.pushButton_last_month.setText(_translate("Form", "←"))
        self.pushButton_next_month.setText(_translate("Form", "→"))
