# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(663, 482)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_clock_in = QtWidgets.QPushButton(Form)
        self.button_clock_in.setGeometry(QtCore.QRect(370, 300, 121, 51))
        self.button_clock_in.setObjectName("button_clock_in")
        self.label_clocked = QtWidgets.QLabel(Form)
        self.label_clocked.setGeometry(QtCore.QRect(340, 150, 211, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_clocked.sizePolicy().hasHeightForWidth())
        self.label_clocked.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_clocked.setFont(font)
        self.label_clocked.setObjectName("label_clocked")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(13, 16, 301, 451))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_time = QtWidgets.QLabel(Form)
        self.label_time.setGeometry(QtCore.QRect(340, 80, 221, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.pushButton_calendar = QtWidgets.QPushButton(Form)
        self.pushButton_calendar.setGeometry(QtCore.QRect(340, 390, 93, 28))
        self.pushButton_calendar.setObjectName("pushButton_calendar")
        self.pushButton_test = QtWidgets.QPushButton(Form)
        self.pushButton_test.setGeometry(QtCore.QRect(460, 390, 121, 28))
        self.pushButton_test.setObjectName("pushButton_test")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "戒色打卡器"))
        self.button_clock_in.setText(_translate("Form", "今日打卡"))
        self.label_clocked.setText(_translate("Form", "你已戒色第0天！"))
        self.pushButton_calendar.setText(_translate("Form", "打开日历"))
        self.pushButton_test.setText(_translate("Form", "打开测试工具箱"))
