# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(539, 439)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 511, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_generate = QtWidgets.QPushButton(self.tab)
        self.pushButton_generate.setGeometry(QtCore.QRect(360, 180, 101, 41))
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 80, 231, 31))
        self.label.setObjectName("label")
        self.lineEdit_data_size = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_data_size.setGeometry(QtCore.QRect(30, 120, 113, 21))
        self.lineEdit_data_size.setObjectName("lineEdit_data_size")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 111, 31))
        self.label_2.setObjectName("label_2")
        self.spinBox_left = QtWidgets.QSpinBox(self.tab)
        self.spinBox_left.setGeometry(QtCore.QRect(30, 250, 46, 22))
        self.spinBox_left.setMinimum(-10)
        self.spinBox_left.setMaximum(0)
        self.spinBox_left.setProperty("value", -2)
        self.spinBox_left.setObjectName("spinBox_left")
        self.spinBox_right = QtWidgets.QSpinBox(self.tab)
        self.spinBox_right.setGeometry(QtCore.QRect(100, 250, 46, 22))
        self.spinBox_right.setMaximum(10)
        self.spinBox_right.setProperty("value", 2)
        self.spinBox_right.setObjectName("spinBox_right")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 210, 261, 16))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 471, 311))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_update = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_update.setGeometry(QtCore.QRect(200, 350, 93, 28))
        self.pushButton_update.setObjectName("pushButton_update")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(30, 170, 211, 41))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_delete = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_delete.setGeometry(QtCore.QRect(310, 180, 93, 28))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "测试工具箱"))
        self.pushButton_generate.setText(_translate("Form", "生成测试数据"))
        self.label.setText(_translate("Form", "需要生成的数据量，请输入正整数"))
        self.lineEdit_data_size.setText(_translate("Form", "10"))
        self.label_2.setText(_translate("Form", "天数的波动范围"))
        self.label_3.setText(_translate("Form", "左边限制为-10到0，右边限制为0到10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "生成测试数据"))
        self.pushButton_update.setText(_translate("Form", "更新展示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "展示解码后的数据"))
        self.pushButton_delete.setText(_translate("Form", "删除选中表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "整表删除"))
