# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(539, 439)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 511, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_generate = QtWidgets.QPushButton(self.tab)
        self.pushButton_generate.setGeometry(QtCore.QRect(360, 180, 101, 41))
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 191, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 210, 261, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 471, 21))
        self.label_4.setObjectName("label_4")
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(self.tab)
        self.dateTimeEdit_start.setGeometry(QtCore.QRect(30, 240, 194, 22))
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(self.tab)
        self.dateTimeEdit_end.setGeometry(QtCore.QRect(240, 240, 194, 22))
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 471, 311))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_update = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_update.setGeometry(QtCore.QRect(200, 350, 93, 28))
        self.pushButton_update.setObjectName("pushButton_update")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(30, 170, 211, 41))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_delete = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_delete.setGeometry(QtCore.QRect(310, 180, 93, 28))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "测试工具箱"))
        self.pushButton_generate.setText(_translate("Form", "生成测试数据"))
        self.label_2.setText(_translate("Form", "请设置测试数据的时间范围"))
        self.label_3.setText(_translate("Form", "左为起始时间，右为终止时间"))
        self.label_4.setText(_translate("Form", "请尽量遵循合理操作，目前误操作处理未完善，请勿乱改导致未知错误"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "生成测试数据"))
        self.pushButton_update.setText(_translate("Form", "更新展示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "展示解码后的数据"))
        self.pushButton_delete.setText(_translate("Form", "删除选中表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "整表删除"))
